// All browser outputs and the importable Workers payload stay in the ignored build tree.
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
await mkdir(new URL('.build/public/assets/', root), { recursive: true });
for (const name of ['index.html', 'workspace.css']) {
  await copyFile(new URL(`ui/${name}`, root), new URL(`.build/public/${name === 'index.html' ? name : `assets/${name}`}`, root));
}
for (const name of ['main.js', 'workspace.js', 'cases.js']) {
  await copyFile(new URL(`.build/browser/ui/${name}`, root), new URL(`.build/public/assets/${name}`, root));
}
const files = {};
for (const name of ['index.html', 'assets/workspace.css', 'assets/main.js', 'assets/workspace.js', 'assets/cases.js']) {
  files[name] = await readFile(new URL(`.build/public/${name}`, root), 'utf8');
}
await writeFile(new URL('.build/ui-content.js', root), `// Generated by build-ui.mjs. Do not edit.\nexport const files = Object.freeze(${JSON.stringify(files)});\n`);
await writeFile(new URL('.build/ui-content.d.ts', root), 'export declare const files: Readonly<Record<string, string>>;\n');
